### PR TITLE
composer: use PSR-4 autoload

### PR DESCRIPTION
**Pull request by TomasVotruba**
PSR-0 is deprecated over a year

### CODE REVIEW

**Comment by liuggio** [comment]
Hi @TomasVotruba  thanks a lot!!
can you please fix the PR `A non-empty PSR-4 prefix must end with a namespace separator.`

I think you have to add the `//` at the end of namespace

**Comment by TomasVotruba** [comment]
Hi, oh sry, I forgot that. Fixed!

**Comment by liuggio** [comment]
:+1:  @TomasVotruba

**Comment by TomasVotruba** [comment]
:+1:

**Comment by liuggio** [comment]
@TomasVotruba I think composer has problem can you run `composer validate` ASAP?

**Comment by TomasVotruba** [comment]
@liuggio Could you link me to the issue?

**Comment by liuggio** [comment]
@TomasVotruba  https://github.com/liuggio/ExcelBundle/issues/96

**Pull request merged**
