### PR TITLE
Added "createReader" function to bundle.

### PR DESCRIPTION
**Pull request by MicioBaus**
Added the "createReader" function of PHPExcel_IOFactory.

### CODE REVIEW

**Comment by liuggio** [comment]
Great!! so fast,
please can you squash commit 2 in 1, 
and please can you add a functional test for it so we will be able to easily accept future PR?

**Comment by MicioBaus** [comment]
Thank you.
Unfortunately I do not really understand your requests (sorry, quite a newbie) ... Could you please provide me some information on how can I perform the actions you requested?
How can I squash the 2 commits?
And how can I implement a functional test?

**Comment by liuggio** [comment]
sure no problem
### Rebase
http://symfony.com/doc/current/contributing/code/patches.html#rework-your-patch 

something like `git rebase -i HEAD~2`

### Tests
Unit you can take inspiration from here: https://github.com/liuggio/ExcelBundle/blob/master/Tests/FactoryTest.php#L12 

there are also functional tests:
a controller: 
https://github.com/liuggio/ExcelBundle/blob/master/Tests/app/Controller/FakeController.php#L10
is tested here:
https://github.com/liuggio/ExcelBundle/blob/master/Tests/Controller/FakeControllerTest.php#L9

**Comment by liuggio** [comment]
@MicioBaus do you need more info? 
I'm really happy to talk more about this.

**Comment by liuggio** [comment]
@MicioBaus ping ...

**Comment by liuggio** [comment]
@MicioBaus

**Comment by vanclei** [comment]
Is there any change this merge happening on Master?

**Comment by vctls** [comment]
@liuggio hi! Is this feature still pending functional tests?
I too would like to use that createReader() function.

**Comment by liuggio** [comment]
@vctls please can you add functional test for it?

**Pull request closed without merging**
