### PR TITLE
Added createReader() factory function and tests.

### PR DESCRIPTION
**Pull request by vctls**
also added necessary routing, and fixed a typo.

### CODE REVIEW

**Comment by vctls** [comment]
Well, actually, that page _does_ 404.

**Comment by liuggio** [comment]
@vctls thanks a lot!!!
(i removed that now :) )

**Comment by vctls** [comment]
Travis is still failing two jobs, though.
This part seems to be the problem, for both errors:
```php
// chack that an empty temporary file cannot be read
$someFile = tmpfile();
$cannotread = $reader->canRead(stream_get_meta_data($someFile)['uri']);
fclose($someFile);
```
Testing the `canRead()` method might not be absolutely vital…
(also there's a typo in my comment)

**Comment by liuggio** [comment]
this fail only on 5.3 version ...

**Comment by vctls** [comment]
and hhvm, too.
For php 5.3, the problem is the array syntax. I should have written something like this:
```php
$metadata = stream_get_meta_data($someFile);
$cannotread = $reader->canRead($metadata ['uri']);
```
And with hhmv, there's an issue with tmpfiles not having an uri:
https://github.com/facebook/hhvm/issues/2336
So I should have used tmpnam() instead.

Want me to fix it?

**Comment by liuggio** [comment]
thanks a lot @vctls we shoud remove from travis the hhvm

**Comment by vctls** [comment]
Fixed: #112
I should have waited for Travis to finish the build on my previous commit to begin with.

**Pull request merged**
